---
- name: Deploy Apache Web Server with Docker
  hosts: webservers
  become: true

  tasks:
    - name: Build Docker image
      command: docker build -t apache-webserver -f ../files/dockerfile ../files
      args:
        chdir: ../files/dockerfile/

    - name: Run Docker container
      docker_container:
        name: apache-container
        image: apache-webserver
        ports:
          - "8080:80"
        restart_policy: always
